### ISSUE TITLE
Schema docs for Telemetry class are missing

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#97] opened 2020-11-18 14:58 UTC
### Environment
 * Telemetry Streaming Version: 1.15.0
 * BIG-IP Version: 15.1.1

### Summary
Schema docs at https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/schema-reference.html#telemetry are missing information on the Telemetry base class

### Steps To Reproduce
1.

### Expected Behavior
Docs should reflect the organization structure of the schema with a description of the allowed entries.

**Comment by dstokesf5** [comment] 2020-11-23 19:04
Confirmed that the Telemetry class is missing from the reference documentation. Added AUTOTOOL-2062 to our internal product backlog to address this.

**Comment by dstokesf5** [comment] 2021-04-05 19:51
It looks like the scripts used to generate that documentation were updated and the `Telemetry` class is now showing up. Closing this issue.

**Closed by dstokesf5** 2021-04-05 19:51 UTC
Labels: bug
