### ISSUE TITLE
Telemetry system streamer fails with a TypeError every time (logs not sent)  

### ISSUE THREAD

**Issue by Eken92** [F5Networks/f5-telemetry-streaming#36] opened 2020-02-24 09:23 UTC
### Environment
 * Telemetry Streaming Version: f5-telemetry-1.9.0-1.noarch
 * BIG-IP Version: BIG-IP 14.1.2.3 Build 0.0.5 Point Release 3

### Summary
When setting up a system streamer on a BIG-IP device, it does only poll logs from the internal rest endpoints, but the transmit to the remote log destination seems to fail. (Nothing is ever sent to it) 

### Steps To Reproduce
1. Submit the following declaration:
```json
 {
        "class": "Telemetry",
        "controls": {
                "class": "Controls",
                "logLevel": "info"
        },
        "My_System": {
                "class": "Telemetry_System",
                "systemPoller": {
                        "interval": 300
                }
        },
        "My_Listener": {
                "class": "Telemetry_Listener",
                "port": 6514
        },
        "My_Consumer": {
                "class": "Telemetry_Consumer",
                "type": "Generic_HTTP",
                "host": "192.168.20.150",
                "protocol": "http",
                "port": 9514,
                "path": "/bigstats",
                "method": "POST",
                "headers": [
                        {
                        "name": "content-type",
                        "value": "application/json"
                        }
                ]
        }
}

```

2. Observe the following error response:
```json
Response is fine for the initial telemetry configuration
```

### Expected Behavior
Logs sent to remote destination

### Actual Behavior
No logs sent and the following stack trace can be seen every 5th minute in the restnoded.log

Mon, 24 Feb 2020 09:01:58 GMT - severe: [telemetry] runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
Traceback:
TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
    at Object.keys.forEach (/var/config/rest/iapps/f5-telemetry/lib/normalizeUtil.js:207:23)
    at Array.forEach (<anonymous>)
    at Object.getAverage (/var/config/rest/iapps/f5-telemetry/lib/normalizeUtil.js:204:27)
    at Object._runCustomFunction (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:165:47)
    at norm.runFunctions.forEach (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:574:36)
    at Array.forEach (<anonymous>)
    at options.normalization.forEach (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:569:39)
    at Array.forEach (<anonymous>)
    at Object.data (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:543:35)
    at SystemStats._processData (/var/config/rest/iapps/f5-telemetry/lib/systemStats.js:150:60)
    at _loadData.then (/var/config/rest/iapps/f5-telemetry/lib/systemStats.js:206:40)
    at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
Mon, 24 Feb 2020 09:01:58 GMT - severe: [telemetry] Error: SystemStats._processProperty: cpu (/mgmt/tm/sys/host-info::sys/host-info/0::sys/hostInfo/0/cpuInfo): Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
Mon, 24 Feb 2020 09:01:58 GMT - severe: [telemetry] Error: SystemStats.collect: Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
Mon, 24 Feb 2020 09:01:58 GMT - severe: [telemetry] systemPoller:safeProcess unhandled exception in promise-chain
Traceback:
Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
    at Object._runCustomFunction (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:168:19)
    at norm.runFunctions.forEach (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:574:36)
    at Array.forEach (<anonymous>)
    at options.normalization.forEach (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:569:39)
    at Array.forEach (<anonymous>)
    at Object.data (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:543:35)
    at SystemStats._processData (/var/config/rest/iapps/f5-telemetry/lib/systemStats.js:150:60)
    at _loadData.then (/var/config/rest/iapps/f5-telemetry/lib/systemStats.js:206:40)
    at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by dstokesf5** [comment] 2020-03-06 21:13
Are you running Telemetry Streaming on a Viprion system? This looks like a possible duplicate of #27.

**Closed by dstokesf5** 2020-03-06 21:13 UTC
Labels: bug, untriaged
